# Generated by Django 4.2.4 on 2023-08-17 11:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('description', models.TextField()),
                ('delivery', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='delivery', to='delivery.location', to_field='zip_code')),
                ('pick_up', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pick_up', to='delivery.location', to_field='zip_code')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('carrying_capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location', to='delivery.location', to_field='zip_code')),
            ],
        ),
    ]
