# Generated by Django 4.2.4 on 2023-08-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Truck',
        ),
    ]
