#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Starting cron"
service cron start

python manage.py migrate
python manage.py load_locations
python manage.py load_trucks
python manage.py crontab add
python manage.py runserver 0.0.0.0:8000
